SP Screen ResDev (Partial)/src/objects/ActionPlan__c.object
<CustomObject>
    <description>Action Plan instance.</description>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>Action_Plans</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>R00NR0000000VZZ8MAO</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <description>The Start Date of the Action Plan</description>
        <inlineHelpText>The Start Date of the Action Plan</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <label>Action Plan</label>
    <nameField>
        <label>Action Plan Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP Screen ResDev (Partial)/src/objects/ActionPlanTemplate__c.object
<CustomObject>
    <description>Template for Action Plan</description>
    <label>Action Plan Template</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Action Plan Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SP Screen ResDev (Partial)/src/objects/APTaskTemplate__c.object
<CustomObject>
    <description>Action Plan Task detail</description>
    <fields>
        <fullName>APTaskTemplate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Task Dependency</label>
        <referenceTo>APTaskTemplate__c</referenceTo>
        <relationshipLabel>AP Tasks</relationshipLabel>
        <relationshipName>R00NR0000000VcWbMAK</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Action_Plan__c</fullName>
        <label>Action Plan</label>
        <referenceTo>ActionPlan__c</referenceTo>
        <relationshipName>R00NR0000000VccFMAS</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ActivityDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DaysFromStart__c</fullName>
        <label>Days After</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Dependent__c</fullName>
        <label>Dependent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>High</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Low</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Reminder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SendEmail__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Send Email Notification of Task creation.</description>
        <label>Send Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Started</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
                <value>
                    <fullName>Waiting on someone else</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Email</fullName>
                </value>
                <value>
                    <fullName>Phone Call</fullName>
                </value>
                <value>
                    <fullName>Mail</fullName>
                </value>
                <value>
                    <fullName>Misc</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>R00NR0000000Vd7NMAS</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>AP Task</label>
    <nameField>
        <label>APTaskTemplate Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AP Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SP Screen ResDev (Partial)/src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

SP Screen ResDev (Partial)/src/classes/TestActionPlanCreationController.cls
@isTest
public class TestActionPlanCreationController
{
    public static testMethod void constructorTests(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan = testUtil.createNewActionPlan( 'contacts', 2 );
        
        System.currentPageReference().getParameters().put( 'id', null );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'clone', '1' );
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        
        ActionPlanTemplate__c apTemplate = testUtil.createNewActionPlanTemplate( 3 );
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'clone', null );
        System.currentPageReference().getParameters().put( 'templateId', apTemplate.Id );
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        
        Contact contact = testUtil.createNewContact();
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', contact.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Contact' );
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        String refid    = apCreateController.refId;
        String reftype  = apCreateController.refType;
        apCreateController.refreshRelatedObjectsLookUp();
        
        Test.StopTest();
    }
    
    public static testMethod void testActionPlanSave(){
        
        //Erase all Action Plans before begining test
        List<ActionPlan__c> apList = [ select Id from ActionPlan__c limit 10000];
        delete apList;
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = new ActionPlan__c();
        
        Contact contact = testUtil.createNewContact();
        
        actionPlan.Name         = testUtil.createRandomWord();
        actionPlan.Contact__c   = contact.Id;
        actionPlan.StartDate__c = Date.today();
        
        APTaskTemplate__c apTask = new APTaskTemplate__c();
        
        apTask.Subject__c           = testUtil.createRandomWord();
        apTask.User__c              = testUtil.createTestUser().Id;
        apTask.DaysFromStart__c     = 2;
        apTask.Type__c              = 'Email';
        apTask.Priority__c          = 'Hight';
                
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', contact.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Contact' );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        
        apCreateController.actionPlans.apTasks = new List<APTaskTemplate__c>();
        apCreateController.actionPlans.apTasks.add( apTask );
        apCreateController.save();
        
        Test.StopTest();
        
        List<ActionPlan__c> results = [ select Id from ActionPlan__c limit 10000];
        
        
        System.assert( !results.isEmpty(), 'Action Plan not created' );
        System.assert( results.size() == 1, 'Action Plan not created' );
        
        apCreateController.cancel();
    }
    
    public static testMethod void testActionPlanSaveAndNew(){
        
        //Erase all Action Plans before begining test
        List<ActionPlan__c> apList = [ select Id from ActionPlan__c limit 10000];
        delete apList;
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = new ActionPlan__c();
        
        Contact contact = testUtil.createNewContact();
        
        actionPlan.Name         = testUtil.createRandomWord();
        actionPlan.Contact__c   = contact.Id;
        actionPlan.StartDate__c = Date.today();
        
        APTaskTemplate__c apTask = new APTaskTemplate__c();
        
        apTask.Subject__c           = testUtil.createRandomWord();
        apTask.User__c              = testUtil.createTestUser().Id;
        apTask.DaysFromStart__c     = 2;
        apTask.Type__c              = 'Email';
        apTask.Priority__c          = 'Hight';
                
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', contact.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Contact' );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        
        apCreateController.actionPlans.apTasks = new List<APTaskTemplate__c>();
        apCreateController.actionPlans.apTasks.add( apTask );
        apCreateController.saveAndNew();
        Test.StopTest();
        List<ActionPlan__c> results = [ select Id from ActionPlan__c limit 10000];
        
        System.assert( !results.isEmpty(), 'Action Plan not created' );
        System.assert( results.size() == 1, 'Action Plan not created' );
        
        
    }
    
    public static testMethod void checkCompletedTasks(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = testUtil.createNewActionPlan( 'accounts', 2 );
        
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        
        Integer numTasksComplete = apCreateController.getCompleted();
        
        System.assert( numTasksComplete == 0 , 'Action plan task completed is incorrect' );
        
        Test.StopTest();
    }
    
    public static testMethod void testAddNewTask(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = testUtil.createNewActionPlan( 'accounts', 2 );
        
        APTaskTemplate__c apTask = new APTaskTemplate__c();
        
        apTask.Action_Plan__c       = actionPlan.Id;
        apTask.Subject__c           = testUtil.createRandomWord();
        apTask.User__c              = testUtil.createTestUser().Id;
        apTask.DaysFromStart__c     = 2;
        apTask.Type__c              = 'Email';
        apTask.Priority__c          = 'Hight';
                
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'add', '1' );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        apCreateController.actionPlans.apTasks = new List<APTaskTemplate__c>();
        apCreateController.actionPlans.apTasks.add( apTask );
        apCreateController.addTask();
        
        Test.StopTest();
    }
    
    public static testMethod void testRemoveActionPlanTask(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = testUtil.createNewActionPlan( 'accounts', 3 );
                
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        System.currentPageReference().getParameters().put( 'remove', '1' );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        apCreateController.actionPlans.apTasks = [ select a.Type__c, a.Subject__c, a.ActivityDate__c, a.Priority__c, a.Status__c, a.Dependent__c, 
                                                        a.Name, a.User__c, a.User__r.Name, a.Id, a.DaysFromStart__c, a.CreatedById, a.APTaskTemplate__r.Name, 
                                                        a.APTaskTemplate__r.Subject__c, a.APTaskTemplate__c, a.Action_Plan__c, a.Reminder__c, 
                                                        a.SendEmail__c, a.Comments__c 
                                                        from APTaskTemplate__c a 
                                                        where a.Action_Plan__c =: actionPlan.Id order by a.createdDate asc ];
                                    
        apCreateController.removeTask();
        
        Test.StopTest();
    }
    
   
    
    public static testMethod void checkSubjectItems(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil   = new ActionPlansTestUtilities();
        ActionPlan__c actionPlan            = testUtil.createNewActionPlan( 'accounts', 2 );
        
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        apCreateController.actionPlans.apTasks = [ select a.Type__c, a.Subject__c, a.ActivityDate__c, a.Priority__c, a.Status__c, a.Dependent__c, 
                                                        a.Name, a.User__c, a.User__r.Name, a.Id, a.DaysFromStart__c, a.CreatedById, a.APTaskTemplate__r.Name, 
                                                        a.APTaskTemplate__r.Subject__c, a.APTaskTemplate__c, a.Action_Plan__c, a.Reminder__c, 
                                                        a.SendEmail__c, a.Comments__c 
                                                        from APTaskTemplate__c a 
                                                        where a.Action_Plan__c =: actionPlan.Id order by a.createdDate asc ];
                                                        
        List<Selectoption> options = apCreateController.getSubjectItems();
        
        System.assert( !options.isEmpty(), 'select options is empty' );
        System.assert( options.size() == 3, 'incorrect number of select options' );
                        
        Test.StopTest();
    }
    
    public static testMethod void testCyclicDependencyTaskSuccess(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
        
        ActionPlan__c actionPlan = testUtil.createNewActionPlan( 'accounts', 0 );
        
        APTaskTemplate__c newAPTask1 = new APTaskTemplate__c();
        APTaskTemplate__c newAPTask2 = new APTaskTemplate__c();
        APTaskTemplate__c newAPTask3 = new APTaskTemplate__c();
        
        newAPTask1.Subject__c           = testUtil.createRandomWord();
        newAPTask1.DaysFromStart__c     = 2;
        newAPTask1.Dependent__c         = '2';
        newAPTask1.Type__c              = 'Email';
        newAPTask1.Priority__c          = 'High';
        newAPTask1.Action_Plan__c       = actionPlan.Id;
        upsert newAPTask1;
        
        newAPTask2.Subject__c           = testUtil.createRandomWord();
        newAPTask2.DaysFromStart__c     = 2;
        newAPTask2.Dependent__c         = 'None';
        newAPTask2.Type__c              = 'Email';
        newAPTask2.Priority__c          = 'High';
        newAPTask2.Action_Plan__c       = actionPlan.Id;
        upsert newAPTask2;
        
        newAPTask3.Subject__c           = testUtil.createRandomWord();
        newAPTask3.DaysFromStart__c     = 2;
        newAPTask3.Dependent__c         = '1';
        newAPTask3.Type__c              = 'Email';
        newAPTask3.Priority__c          = 'High';
        newAPTask3.Action_Plan__c       = actionPlan.Id;
        upsert newAPTask3;
        
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        
        apCreateController.actionPlans.apTasks = new List<APTaskTemplate__c>();
        apCreateController.actionPlans.apTasks.add( newAPTask1 );
        apCreateController.actionPlans.apTasks.add( newAPTask2 );
        apCreateController.actionPlans.apTasks.add( newAPTask3 );
        
        apCreateController.save();
        
        System.assert( apCreateController.getErrorMsg() == '' );
        
        Test.StopTest();
    }
    
    public static testMethod void testCyclicDependencyTasksFail(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
        
        ActionPlan__c actionPlan = testUtil.createNewActionPlan( 'accounts', 0 );
        
        APTaskTemplate__c newAPTask1 = new APTaskTemplate__c();
        APTaskTemplate__c newAPTask2 = new APTaskTemplate__c();
        APTaskTemplate__c newAPTask3 = new APTaskTemplate__c();
        
        newAPTask1.Subject__c           = testUtil.createRandomWord();
        newAPTask1.DaysFromStart__c     = 2;
        newAPTask1.Dependent__c         = '2';
        newAPTask1.Type__c              = 'Email';
        newAPTask1.Priority__c          = 'Hight';
        
        newAPTask2.Subject__c           = testUtil.createRandomWord();
        newAPTask2.DaysFromStart__c     = 2;
        newAPTask2.Dependent__c         = '0';
        newAPTask2.Type__c              = 'Email';
        newAPTask2.Priority__c          = 'Hight';
        
        newAPTask3.Subject__c           = testUtil.createRandomWord();
        newAPTask3.DaysFromStart__c     = 2;
        newAPTask3.Dependent__c         = '1';
        newAPTask3.Type__c              = 'Email';
        newAPTask3.Priority__c          = 'Hight';
        
        System.currentPageReference().getParameters().put( 'id', actionPlan.Id );
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( actionPlan ) );
        
        apCreateController.actionPlans.apTasks = new List<APTaskTemplate__c>();
        apCreateController.actionPlans.apTasks.add( newAPTask1 );
        apCreateController.actionPlans.apTasks.add( newAPTask2 );
        apCreateController.actionPlans.apTasks.add( newAPTask3 );
        
        apCreateController.save();
        
        System.assert( apCreateController.getErrorMsg() != null );
        
        Test.StopTest();
    }
    
    public static testMethod void checkReferedObject(){
        
        Test.StartTest();
        
        ActionPlansTestUtilities testUtil = new ActionPlansTestUtilities();
        
        Contact contact         = testUtil.createNewContact();
        Account account         = testUtil.createNewAccount();
        Lead lead               = testUtil.createNewLead();
        Opportunity opportunity = testUtil.createNewOpportunity();  
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', contact.id );
        System.currentPageReference().getParameters().put( 'refType', 'Contact' );
        
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        apCreateController.referedObjectInit();
        apCreateController.referedObjectOwnerInit();
        
        System.assert( apCreateController.relatedObjNameList.size() == 2 );
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', account.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Account' );
        
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        apCreateController.referedObjectInit();
        apCreateController.referedObjectOwnerInit();
        
        System.assert( apCreateController.relatedObjNameList.size() == 2 );
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', lead.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Lead' );
        
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        apCreateController.referedObjectInit();
        apCreateController.referedObjectOwnerInit();
        
        System.assert( apCreateController.relatedObjNameList.size() == 2 );
        
        System.currentPageReference().getParameters().put( 'id', null );
        System.currentPageReference().getParameters().put( 'refId', opportunity.Id );
        System.currentPageReference().getParameters().put( 'refType', 'Opportunity' );
        
        apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        apCreateController.referedObjectInit();
        apCreateController.referedObjectOwnerInit();
        
        System.assert( apCreateController.relatedObjNameList.size() == 2 );
        System.assert( apCreateController.getRelatedObjectOptions().size() == apCreateController.actionPlans.getRelatedObjectOptions().size() );
        
        Test.StopTest();
    }
    
    
    //aPTemplateExists
    public static testMethod void test_aPTemplateExists(){
        
        Test.StartTest();
        ActionPlanCreationController apCreateController = new ActionPlanCreationController( new Apexpages.StandardController( new ActionPlan__c() ) );
        
        ApexPages.currentPage().getParameters().put( 'refType','FOO' );
        ApexPages.currentPage().getParameters().put( 'refId','FOO' );
        delete [select Id from ActionPlanTemplate__c];
        
        System.assertEquals(apCreateController.aPTemplateExists,false);
        
        Test.StopTest();
    }    
    
    
}